### ISSUE TITLE
Not compatible with browserify

### ISSUE THREAD

**Issue by christophercliff** [neocotic/europa#44]
Run command:

```
$ browserify ./your-module.js
```

Throws:

```
Error: module "canvas" not found from "/node_modules/html-md/node_modules/jsdom/lib/jsdom/level2/html.js"
```

Where `your-module.js` requires `html-md`. Tested with browserify v3.5.0, html-md v3.0.2.

**Comment by mstewart20** [comment]
@christophercliff:

Just wanted to add that if you are *only* using html-md within a browserify-based project, you can solve this by telling browserify to ignore `require("jsdom")`. This works because there is already a check for the `window` global within html-md, if it finds it then the `require("jsdom")` is never actually executed.

In my gulp file, I used:

```javascript
var b = browserify({
  //options here
});

b.ignore("jsdom");

//Continue on your merry way
```

Hope that helps!

**Comment by mstewart20** [comment]
Oops, didn't realize this was a year old...i'm still stuck in 2014 apparently.
